# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'shopping-go' do
  use_frameworks!
pod 'AFNetworking'
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'YYModel'
pod 'MJRefresh'
pod 'FMDB'
pod 'MagicalRecord'
pod 'Masonry'
pod 'PPNumberButton'

end
